# .github/workflows/terraform_plan.yml
name: Terraform Plan

on:
  workflow_call:
    inputs:
      terraform_version:
        required: true
        type: string

jobs:
  plan:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: ${{ inputs.terraform_version }}
    
    # - name: Terraform Init
    #   run: terraform init
    
    # - name: Terraform Plan
    #   run: terraform plan
